# Script tutorial - Multi-Layer Perceptron

O Perceptron de Múltiplas Camadas (MLP) é uma arquitetura de rede neural artificial amplamente estudada e aplicada em problemas de aprendizado supervisionado. Sua fundação teórica está enraizada na teoria dos perceptrons, desenvolvida inicialmente por Frank Rosenblatt em 1958. Os perceptrons são modelos simplificados de neurônios biológicos que podem receber entradas, aplicar pesos a essas entradas e produzir uma saída binária com base em uma função de ativação.

No entanto, os perceptrons individuais têm limitações significativas em termos de complexidade e capacidade de modelagem. Para superar essas limitações, o MLP foi proposto como uma extensão dos perceptrons simples, introduzindo múltiplas camadas de neurônios interconectados. Isso permitiu que o modelo aprendesse representações hierárquicas e não lineares dos dados, aumentando drasticamente sua capacidade de generalização e resolução de problemas mais complexos.

A teoria subjacente ao treinamento do MLP envolve a minimização de uma função de perda, que quantifica a diferença entre as previsões do modelo e os valores reais. Para isso, é utilizado o algoritmo de retropropagação (backpropagation), que calcula o gradiente da função de perda em relação aos pesos da rede e ajusta esses pesos de forma iterativa usando métodos de otimização, como descida de gradiente estocástica.

Um aspecto crucial na teoria do MLP é a escolha da função de ativação, que determina a saída de cada neurônio com base em suas entradas ponderadas. Funções de ativação comuns incluem a função sigmoide, a função de tangente hiperbólica e a função ReLU (Rectified Linear Unit), cada uma com suas próprias características e propriedades matemáticas que afetam o comportamento e o desempenho do modelo.

Além disso, a arquitetura do MLP, incluindo o número de camadas ocultas, o número de neurônios em cada camada e a conectividade entre as camadas, também desempenha um papel fundamental em sua capacidade de aprendizado e generalização. Encontrar a configuração ideal da rede é muitas vezes uma tarefa desafiadora que envolve experimentação e ajuste cuidadoso de hiperparâmetros.

Em resumo, o MLP representa um marco importante na teoria e prática do aprendizado de máquina, oferecendo uma abordagem flexível e poderosa para a modelagem de dados complexos e a resolução de uma ampla gama de problemas de aprendizado supervisionado. Sua fundamentação teórica em princípios de redes neurais e algoritmos de otimização o torna uma ferramenta fundamental no arsenal de técnicas de aprendizado de máquina.

# Funcionamento do Script utilizando Multi Layer Perceptron para Regressão

1 - Importação de Bibliotecas: O script começa importando as bibliotecas necessárias, incluindo pandas para manipulação de dados, scikit-learn para construção do modelo de Multi Layer Perceptron e métricas de avaliação.

In [1]:
# Importando as bibliotecas necessárias
import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np

2 - Carregamento dos Dados: Em seguida, o script carrega os dados do arquivo de texto "DadosBancarios.txt" utilizando a função 'pd.read_csv()'. Esta etapa é crucial para preparar os dados para treinamento e teste do modelo.

In [2]:
# Carregando os dados do arquivo txt
dados = pd.read_csv('DadosBancarios.txt', sep=',')  

3 - Visualização dos Dados: O script exibe os primeiros registros do conjunto de dados carregados usando 'print(dados.head())'. Isso permite uma rápida inspeção dos dados para garantir que foram carregados corretamente.

In [3]:
# Visualizando os primeiros registros do conjunto de dados
print("Visualização dos primeiros registros do conjunto de dados:")
print(dados.head())

Visualização dos primeiros registros do conjunto de dados:
   ID  Idade  Saldo  Emprestimo Aprovado EstadoCivil CartaoCredito
0   1     35   5000           0        S   NaoCasado             S
1   2     45   8000        2000        S      Casado             S
2   3     30   2000           0        N   NaoCasado             N
3   4     55  10000        5000        S  Divorciado             S
4   5     40   6000        1000        S      Casado             S


4 - Preparação dos Dados: 
    
    'LabelEncoder()': Este é um objeto da classe LabelEncoder do scikit-learn, que é usada para codificar variáveis categóricas em números inteiros.
    
    O método fit_transform()' ajusta o LabelEncoder ao conjunto de dados e, em seguida, transforma os valores da coluna 'EstadoCivil' de strings em números inteiros.
    
    O conjunto de dados é dividido em features (X) e target (y), onde as features são todas as colunas, exceto a coluna "Aprovado", que é nossa variável alvo. Isso é feito usando o método 'drop()' do pandas.

In [4]:
# Codificação de rótulos para variável categórica "Aprovado"
le = LabelEncoder()
dados['Aprovado'] = le.fit_transform(dados['Aprovado'])

# Codificação de rótulos para variável categórica "cartao de credito"
dados['CartaoCredito'] = le.fit_transform(dados['CartaoCredito'])

# Codificação de rótulos para variável categórica "EstadoCivil"
dados['EstadoCivil'] = le.fit_transform(dados['EstadoCivil'])

# Separando as features (atributos) e o target (variável que queremos prever)
X = dados.drop('Emprestimo', axis=1)  # Features
y = dados['Emprestimo']  # Target

print("X = \n", X.head())
print("\nY = \n", y.head())

X = 
    ID  Idade  Saldo  Aprovado  EstadoCivil  CartaoCredito
0   1     35   5000         1            2              1
1   2     45   8000         1            0              1
2   3     30   2000         0            2              0
3   4     55  10000         1            1              1
4   5     40   6000         1            0              1

Y = 
 0       0
1    2000
2       0
3    5000
4    1000
Name: Emprestimo, dtype: int64


5 - Divisão em Conjuntos de Treinamento e Teste: Os dados são divididos em conjuntos de treinamento e teste usando a função 'train_test_split()' do scikit-learn. Isso permite avaliar a capacidade do modelo de generalizar para novos dados não vistos.

In [5]:
# Dividindo o conjunto de dados em conjunto de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Conjunto de treinamento: \n")
print("\nX_train = \n", X_train.head())
print("\nY_train = \n", y_train.head())
print("\nConjunto de teste: \n")
print("\nX_test = \n", X_test.head())
print("\nY_test = \n", y_test.head())

Conjunto de treinamento: 


X_train = 
     ID  Idade  Saldo  Aprovado  EstadoCivil  CartaoCredito
9   10     28   4000         0            2              0
13  14     37   6200         1            2              1
1    2     45   8000         1            0              1
22  23     49   9200         1            0              1
5    6     25   3000         0            2              0

Y_train = 
 9      500
13    1500
1     2000
22    5000
5        0
Name: Emprestimo, dtype: int64

Conjunto de teste: 


X_test = 
     ID  Idade  Saldo  Aprovado  EstadoCivil  CartaoCredito
8    9     42   7000         1            0              1
16  17     52  11000         1            0              1
0    1     35   5000         1            2              1
23  24     34   5400         1            0              1
11  12     33   4800         1            1              1

Y_test = 
 8     3000
16    7000
0        0
23    1600
11     800
Name: Emprestimo, dtype: int64


6 - Construção e Treinamento do Modelo: O script cria um classificador de Multi Layer Perceptron usando 'MLPRegressor()' do scikit-learn. Este classificador é treinado com os dados de treinamento usando o método 'fit()'.

In [6]:
# Criando o regressor MLP
mlp_regressor = MLPRegressor(hidden_layer_sizes=(100, 50), activation='relu',
                             solver='adam', random_state=42)

# Treinando o modelo
mlp_regressor.fit(X_train, y_train)

MLPRegressor(hidden_layer_sizes=(100, 50), random_state=42)

7 - Avaliação do Modelo: Após o treinamento, o modelo é avaliado usando os dados de teste. As previsões são feitas para os dados de teste usando predict() e o erro médio quadrático do modelo é calculada usando mean_squared_error() do scikit-learn.
    
Exibição do erro médio quadrático (MSE) e a raiz o erro médio quadrático (RMSE): Por fim, o script imprime o erro médio quadrático (MSE) e sua raiz (RMSE) do modelo, que é uma medida da precisão das previsões do modelo em relação aos rótulos verdadeiros dos dados de teste.

In [7]:
# Fazendo previsões no conjunto de teste
y_pred = mlp_regressor.predict(X_test)

print("Previsões do modelo para o conjunto de teste: ")
print(y_pred)

print("\nConjunto de teste (y_test):")
print(y_test)

# Calculando o erro médio quadrático (MSE) do modelo
mse = mean_squared_error(y_test, y_pred)
print("\nErro médio quadrático do modelo:", mse)

# Calculando o RMSE do modelo
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("\nRMSE do modelo:", rmse)

Previsões do modelo para o conjunto de teste: 
[3888.63522908 6113.30449843 2776.96508483 2999.96389179 2666.09833756]

Conjunto de teste (y_test):
8     3000
16    7000
0        0
23    1600
11     800
Name: Emprestimo, dtype: int64

Erro médio quadrático do modelo: 2945931.693795328

RMSE do modelo: 1716.3716654021437


Créditos:
- Patrick dos Santos Câmara
- ChatGPT